"""Initial migration

Revision ID: 920d0d9f6f3c
Revises: 
Create Date: 2025-11-21 11:36:20.705038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920d0d9f6f3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_code'), 'faculties', ['code'], unique=True)
    op.create_index(op.f('ix_faculties_id'), 'faculties', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_years >= 1 AND duration_years <= 6', name='ck_programs_duration_range'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_index(op.f('ix_programs_faculty_id'), 'programs', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('course_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('semester in (1, 2)', name='ck_course_unit_semester_1_2'),
    sa.CheckConstraint('year >= 1', name='ck_course_unit_year_positive'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_units_code'), 'course_units', ['code'], unique=False)
    op.create_index(op.f('ix_course_units_id'), 'course_units', ['id'], unique=False)
    op.create_index(op.f('ix_course_units_program_id'), 'course_units', ['program_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='userrole'), server_default='student', nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_faculty_id'), 'users', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_program_id'), 'users', ['program_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('user_login', 'user_logout', 'user_registered', 'resource_uploaded', 'resource_downloaded', 'resource_deleted', 'course_created', 'course_updated', 'course_deleted', 'faculty_created', 'faculty_updated', 'program_created', 'program_updated', 'user_role_changed', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_unit_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_download_at', sa.DateTime(), nullable=True),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_unit_id', 'sha256', name='uq_resource_courseunit_sha256')
    )
    op.create_index(op.f('ix_resources_course_unit_id'), 'resources', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_sha256'), 'resources', ['sha256'], unique=False)
    op.create_index(op.f('ix_resources_uploader_id'), 'resources', ['uploader_id'], unique=False)
    op.create_table('resource_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_bookmark_user_resource')
    )
    op.create_index(op.f('ix_resource_bookmarks_id'), 'resource_bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_resource_bookmarks_resource_id'), 'resource_bookmarks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_bookmarks_user_id'), 'resource_bookmarks', ['user_id'], unique=False)
    op.create_table('resource_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_comments_id'), 'resource_comments', ['id'], unique=False)
    op.create_index(op.f('ix_resource_comments_resource_id'), 'resource_comments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_comments_user_id'), 'resource_comments', ['user_id'], unique=False)
    op.create_table('resource_download_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_download_events_id'), 'resource_download_events', ['id'], unique=False)
    op.create_index(op.f('ix_resource_download_events_resource_id'), 'resource_download_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_download_events_user_id'), 'resource_download_events', ['user_id'], unique=False)
    op.create_table('resource_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_rating_user_resource')
    )
    op.create_index(op.f('ix_resource_ratings_id'), 'resource_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_resource_ratings_resource_id'), 'resource_ratings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_ratings_user_id'), 'resource_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_ratings_user_id'), table_name='resource_ratings')
    op.drop_index(op.f('ix_resource_ratings_resource_id'), table_name='resource_ratings')
    op.drop_index(op.f('ix_resource_ratings_id'), table_name='resource_ratings')
    op.drop_table('resource_ratings')
    op.drop_index(op.f('ix_resource_download_events_user_id'), table_name='resource_download_events')
    op.drop_index(op.f('ix_resource_download_events_resource_id'), table_name='resource_download_events')
    op.drop_index(op.f('ix_resource_download_events_id'), table_name='resource_download_events')
    op.drop_table('resource_download_events')
    op.drop_index(op.f('ix_resource_comments_user_id'), table_name='resource_comments')
    op.drop_index(op.f('ix_resource_comments_resource_id'), table_name='resource_comments')
    op.drop_index(op.f('ix_resource_comments_id'), table_name='resource_comments')
    op.drop_table('resource_comments')
    op.drop_index(op.f('ix_resource_bookmarks_user_id'), table_name='resource_bookmarks')
    op.drop_index(op.f('ix_resource_bookmarks_resource_id'), table_name='resource_bookmarks')
    op.drop_index(op.f('ix_resource_bookmarks_id'), table_name='resource_bookmarks')
    op.drop_table('resource_bookmarks')
    op.drop_index(op.f('ix_resources_uploader_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_sha256'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_course_unit_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_program_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_faculty_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_course_units_program_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_code'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_faculty_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_faculties_id'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_code'), table_name='faculties')
    op.drop_table('faculties')
    # ### end Alembic commands ###
