"""add_banner_url_to_users

Revision ID: c85a713c6dbb
Revises: 5003eafd9450
Create Date: 2025-12-08 15:51:41.160598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85a713c6dbb'
down_revision: Union[str, None] = '5003eafd9450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_url')
    # ### end Alembic commands ###
